@flaas_HostAddress = http://10.0.1.236:5112

GET {{flaas_HostAddress}}/
Accept: application/json

###

POST {{flaas_HostAddress}}/on

###

POST {{flaas_HostAddress}}/off

###

POST {{flaas_HostAddress}}/brightness
Content-Type: application/json

{
    "brightness": 77.7
}

###

POST {{flaas_HostAddress}}/
Content-Type: application/json

{
    "isOn": false,
    "brightness": 80
}

###

POST {{flaas_HostAddress}}/
Content-Type: application/json

{
    "isOn": true,
    "brightness": 100
}

###
